# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_isim', models.CharField(max_length=100, verbose_name='Albüm İsim')),
                ('sanatci_isim', models.CharField(max_length=100, verbose_name='Sanatçı İsim')),
                ('album_tur', models.CharField(max_length=100, verbose_name='Albüm Tür')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Albüm Çıkış Tarihi')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorilerine Ekle')),
                ('album_logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
