# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180901_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
