# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20180908_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarki',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
