# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-08 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_sarki_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarki',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
